services:
  # Base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: app_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped
    ports:
      - "${BD_OUTPUT_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: ${START_PERIOD:-5}s

  # Cache/Broker Redis
  redis:
      image: redis:7-alpine
      container_name: app_redis
      ports:
        - "${REDIS_CACHE_PORT}:6379"
      command: redis-server --appendonly yes # Active la persistance sur disque
      volumes:
        - redis_data:/data # Persistance réelle des données Redis
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 20s
        timeout: 10s
        retries: 10
        start_period: ${START_PERIOD:-5}s
      restart: unless-stopped

  # Backend FastAPI
  api:
    build: .
    container_name: app_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "${API_PORT:-8000}:8000"      # Expose le port 8000 de l'API sur le port défini dans .env ou 8000 par défaut
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: ${START_PERIOD:-5}s
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy



  # Workers Celery (Tâches de fond)
#  worker:
#    build: .
#    container_name: app_default_worker
#    command: celery -A app.worker.celery_app worker --loglevel=info --concurrency=5 --max-tasks-per-child=10 -n default_worker@%h
#     # --concurrency=2 : Limite à 2 tâches simultanées pour éviter de surcharger le serveur
#     # --max-tasks-per-child=10 : Redémarre le worker après 10 tâches pour libérer la mémoire (utile si certaines tâches sont gourmandes en RAM)
#    volumes:
#      - .:/app
#    restart: unless-stopped
#    depends_on:
#      db:
#        condition: service_healthy
#      redis:
#        condition: service_healthy


volumes:
  db_data:
  redis_data:


