"""Schema Initial

Revision ID: d8084add8f60
Revises: 
Create Date: 2026-06-14 08:33:14.357343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8084add8f60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ADMIN', 'USER', name='usertype').create(op.get_bind())
    sa.Enum('F', 'M', name='sexetype').create(op.get_bind())
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('sexe', postgresql.ENUM('F', 'M', name='sexetype', create_type=False), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='usertype', create_type=False), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_created_at_id', 'users', ['created_at', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_users_role', 'users', ['role'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_users_username', 'users', ['username'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='chk_sessions_expires_after_creation'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_sessions_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('idx_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_ref_token_hash', 'sessions', ['refresh_token_hash'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id', 'last_activity_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_ref_token_hash', table_name='sessions')
    op.drop_index('idx_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('uq_users_username', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_role', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_deleted_at', table_name='users', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_index('idx_users_created_at_id', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    sa.Enum('F', 'M', name='sexetype').drop(op.get_bind())
    sa.Enum('ADMIN', 'USER', name='usertype').drop(op.get_bind())
    # ### end Alembic commands ###
